### PR TITLE
add accumulator tank to limit inverted flight

### PR DESCRIPTION
**Pull request by alexeijd**
- accumulator added for 5 seconds afterburner limit (more than 15 secs
mil power)
 - feed changed to accumulator
 - main tank reduced by size of accumulator
 - logic for main to accumulator flow
 - summers for main & accumulator

### CODE REVIEW

**Comment by l0k1** [comment]
Thanks for the work! I loaded it up and it was losing fuel at a very quick pace, however. tank[2] is always flowing into tank[14], even though tank[14] is full, so the excess fuel was just discarded and it looks like the plane was using fuel fast.

I'd double check your switch logic on line 244  real quick, that looks like it's where the error is coming from.

Thanks again!

**Comment by alexeijd** [comment]
Bugger - must have missed something 

Will check it when I get home tonight

**Comment by l0k1** [comment]
Found the issue, there's a typo on line 249. I'll let you fix it and then I'm 100% comfortable merging it. ;)

**Comment by alexeijd** [comment]
thanks for the hint - long day at work today :/

**Comment by l0k1** [comment]
I hear that.

Merging, good work and thanks!

**Pull request merged**
